version: '3'
services:
  db:
    image: mongo:5.0.0
    container_name: jira-app
    restart: 'no'
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      MONGODB_DATABASE: jira-app
